language: go

go:
  - 1.12.x

before_install:
  - go get -u golang.org/x/lint/golint

script:
  - env GO111MODULE=on make lint
  - env GO111MODULE=on make test
  - env GO111MODULE=on make build

notifications:
  email: false
