FROM golang:1.12

WORKDIR /overmoon
COPY src /overmoon/src
COPY go.mod go.sum /overmoon/

RUN go build src/bin/proxy/proxy.go
RUN rm -rf src
RUN rm go.mod go.sum

# Mount new codes into the container.
VOLUME /overmoon/src
VOLUME /overmoon/go.mod /overmoon/go.sum
VOLUME /overmoon/shared
VOLUME /overmoon/copy_target.sh
